apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: qr5bmy7k4-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/qr5bmy7k4-dotnet-basic-gitops